### PR TITLE
Add class_interface method to call services through class directly

### PR DESCRIPTION
**Pull request by getand**
This was an idea that would allow to call services directly from the class level. A bit of sugar?

### CODE REVIEW

**Review by the-wendell — APPROVED** [review]
I like it.  I used something similar in my first job.  No need to call `#new`.

**Review by nsommer — APPROVED** [review]
👍 - We should align internally if/when/how to use it though.

**Comment by AkihikoITOH** [comment]
I love the idea. Honestly I've been wondering why we don't do this since the day one😄

Although, I'm not entirely sure if this should be a part of `nxt_init`. This addition doesn't have much to do with what `nxt_init` has been doing. The scope of `nxt_init`'s functionality is now broaden slightly from

> Create an initializer that accepts option arguments and define private readers for your arguments at the same time.

to "scaffolding class definition".

Updating README accordingly should be enough in my opinion though.

**Review by AkihikoITOH — APPROVED** [review]

**Review by aquint — APPROVED** [review]
Yes, love the idea!

**Comment by getand** [comment]
> I love the idea. Honestly I've been wondering why we don't do this since the day one😄
> 
> Although, I'm not entirely sure if this should be a part of `nxt_init`. This addition doesn't have much to do with what `nxt_init` has been doing. The scope of `nxt_init`'s functionality is now broaden slightly from
> 
> > Create an initializer that accepts option arguments and define private readers for your arguments at the same time.
> 
> to "scaffolding class definition".
> 
> Updating README accordingly should be enough in my opinion though.

Agree. Had the same feeling. Does not belong here. Probably we should make a `NxtService` gem that makes some assumptions how a service object behaves and provides this interface but also includes `NxtInit`. What do you think @AkihikoITOH ? Might even be useful to have this to enforces all services to behave the same.

And if you wondered why it's not there, why did you not build it @AkihikoITOH ?

**Comment by AkihikoITOH** [comment]
> > I love the idea. Honestly I've been wondering why we don't do this since the day one😄
> > Although, I'm not entirely sure if this should be a part of `nxt_init`. This addition doesn't have much to do with what `nxt_init` has been doing. The scope of `nxt_init`'s functionality is now broaden slightly from
> > > Create an initializer that accepts option arguments and define private readers for your arguments at the same time.
> > 
> > 
> > to "scaffolding class definition".
> > Updating README accordingly should be enough in my opinion though.
> 
> Agree. Had the same feeling. Does not belong here. Probably we should make a `NxtService` gem that makes some assumptions how a service object behaves and provides this interface but also includes `NxtInit`. What do you think @AkihikoITOH ? Might even be useful to have this to enforces all services to behave the same.
> 

That would be good I think. I was also thinking about separate (sub) modules within the same gem. On the other hand, the current way is practical as we almost always use them in combination either for service classes or factory classes.

Ideally we create a new gem (`nxt_scaffold` or something) and put `NxtInit` and `NxtInterface` in it and perhaps some bundle modules such as `NxtService` or `NxtFactory`. But it sounds like an overkill. To be honest I'd be fine with just updating README at this point.

> And if you wondered why it's not there, why did you not build it @AkihikoITOH ?

It's "nice to have, but I can live without it" kind of thing and didn't really feel an urge to do something about it 😄

**Review by rkallensee — APPROVED** [review]

**Pull request closed without merging**
